FROM centos:7
USER root
ENV LOGS_CONTAINER_ID=123
ENV LOGSTASH_PORT=9500
RUN yum clean all & yum install -y docker telnet
WORKDIR /home/
RUN touch log.out
COPY ./entrypoint.sh /home
RUN chmod +x /home/entrypoint.sh
ENTRYPOINT ["/home/entrypoint.sh"]

