apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    app: website
spec:
  containers:
  - name: website
    image: yageldhn/website_k8s:latest
    ports:
    #- containerPort: 5000
    - containerPort: 80
