apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  ports:
  - port: 9500
    name: serving
    protocol: TCP
  - port: 5044
    name: node2node
    protocol: TCP
  selector:
    app: logstash
