FROM php:7.0-apache
#RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN echo "ServerName 0.0.0.0" >> /etc/apache2/apache2.conf # FOR KUBERENTES
COPY ./index.php /var/www/html/
EXPOSE 5000
